#Workflow files are the recipe for task automation. This is where actions are placed if I want to use them for a task.
name: JS Actions

on: #[push]
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: ha-ha
        uses: ./.github/actions/joke-action
        id: jokes

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GIITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}

